# Домашнее задание №4

**1. (20 баллов)**

Для папки Corel необходимо для каждого изображения, предварительно переведенного в HSV, посчитать гистограмму 
(шаг квантования выберите самостоятельно). 
После этого вычислить попарные расстояния между гистограммами с помощью метрик L2 и Хи-квадрат.
Отсортировать полученные пары и записать имена и расстояния в файл (для каждой метрики свой, 
т.е. в конечном итоге будет два файла) в формате:
$$
img\_name1 \hphantom aimg\_name23 \hphantom a 66.3$$
$$
img\_name5 \hphantom aimg\_name66 \hphantom a 77.1,
$$
где в каждой строчке записаны два имени файла и расстояние между изображениями, скрывающимися за этими именами.
Обратите внимание, что тут происходит некоторое определение расстояния между изображениями, 
а значит результат не должен быть совсем уж хаотичным, там есть группы похожих друг на друга изображений.

In [1]:
from os import listdir
from os.path import isfile, join
img_dir = "datasets/Corel"
fnames = [join(img_dir, f) for f in listdir(img_dir) if isfile(join(img_dir, f))]

In [2]:
import numpy as np
import cv2
import matplotlib.pylab as plt
%matplotlib inline

def show_gray(img):
    ax = plt.axes([0,0,1,1], frameon=False)
    ax.set_axis_off()
    plt.imshow(img, cmap="gray")

def show_rgb(img):
    ax = plt.axes([0,0,1,1], frameon=False)
    ax.set_axis_off()
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

def show(img):
    if img.ndim == 3:
        show_rgb(img)
    else:
        show_gray(img)

In [3]:
images = [cv2.imread(f) for f in fnames]
hsv_images = [cv2.cvtColor(img, cv2.COLOR_BGR2HSV) for img in images]

In [12]:
n = len(hsv_images)
tmp = [hsv_images[0], hsv_images[1]]
m = len(tmp)
histograms = cv2.calcHist(tmp, [2] * m , None, [32] * m, [0, 256] * m)

print(tmp[0])
# print(cv2.compareHist(histograms[0], histograms[1], cv2.HISTCMP_CHISQR))

# histograms = cv2.calcHist(hsv_images, [2] * n , None, [32] * n, [0, 256] * n)

[[[110 190 134]
  [110 189 135]
  [110 186 137]
  ..., 
  [110 201 127]
  [110 201 127]
  [110 201 127]]

 [[110 190 134]
  [110 189 135]
  [110 186 137]
  ..., 
  [110 201 127]
  [110 201 127]
  [110 201 127]]

 [[110 189 135]
  [110 188 136]
  [110 186 137]
  ..., 
  [110 201 127]
  [110 201 127]
  [110 201 127]]

 ..., 
 [[ 40 162  96]
  [ 40 167  93]
  [ 40 171  91]
  ..., 
  [ 44 136 120]
  [ 44 136 120]
  [ 43 131 119]]

 [[ 42 160  89]
  [ 42 160  89]
  [ 42 160  89]
  ..., 
  [ 42 147 113]
  [ 42 148 112]
  [ 42 149 111]]

 [[ 42 166  86]
  [ 42 166  86]
  [ 42 166  86]
  ..., 
  [ 42 147 113]
  [ 42 149 111]
  [ 42 149 111]]]


**2. (20 баллов)**
Для папки leaves для каждого контура листа необходимо посчитать дескрипторы Фурье. После этого вычислить попарные расстояния между контурами (используйте метрику L2 для сравнения набора дескрипторов). Отсортировать полученные пары и записать имена в файл в формате, обозначенном в первом пункте.

Реализуте функцию, которая выводит на экран n самых лучших пар. 

In [6]:
def show_nearest(n, filename):
    pass

show_nearest(20,'Corel_L2.txt')
show_nearest(20,'Corel_Chi-squared.txt')
show_nearest(20,'Leaves_L2.txt')